import { registry, walk, validateProject } from "./model.mjs";
const str = (s) =>
  '"' +
  String(s ?? "")
    .replace(/\\/g, "\\\\")
    .replace(/"/g, '\\"')
    .replace(/\r/g, "\\r")
    .replace(/\n/g, "\\n")
    .replace(/\t/g, "\\t")
    .replace(
      /[\u0000-\u0008\u000b\u000c\u000e-\u001f\u2028\u2029]/g,
      (c) => "\\u" + c.charCodeAt(0).toString(16).padStart(4, "0"),
    ) +
  '"';
export function expression(e, depth = 0) {
  if (depth > 64) throw new Error("Expression nesting exceeds 64.");
  if (e === undefined || e === null) return "null";
  if (typeof e !== "object") return String(e);
  switch (e.kind) {
    case "text":
      return str(e.value);
    case "number":
      return Number.isFinite(Number(e.value)) ? String(Number(e.value)) : "0";
    case "boolean":
      return e.value === true || e.value === "true" ? "true" : "false";
    case "null":
      return "null";
    case "reference":
    case "raw":
      return String(e.value || "null");
    case "binary":
      if (
        ![
          "+",
          "-",
          "*",
          "/",
          "%",
          "==",
          "!=",
          ">",
          "<",
          ">=",
          "<=",
          "&&",
          "||",
          "??",
        ].includes(e.op)
      )
        throw new Error("Invalid expression operator.");
      return (
        "(" +
        expression(e.left, depth + 1) +
        " " +
        e.op +
        " " +
        expression(e.right, depth + 1) +
        ")"
      );
    case "not":
      return "!(" + expression(e.value, depth + 1) + ")";
    case "vector":
      return (
        "new Vector3((float)(" +
        expression(e.x, depth + 1) +
        "), (float)(" +
        expression(e.y, depth + 1) +
        "), (float)(" +
        expression(e.z, depth + 1) +
        "))"
      );
    default:
      throw new Error("Unknown expression kind.");
  }
}
const ex = (v, k) => expression(v[k]);
const args = (v) => (v.args || []).map((e) => expression(e)).join(", ");
export function generateProject(project) {
  validateProject(project);
  const diagnostics = [],
    files = [];
  for (const file of project.files) {
    const lines = [],
      map = {};
    let indent = 0;
    const emit = (text = "", id) => {
      for (const line of String(text).split(/\r?\n/)) {
        lines.push("    ".repeat(Math.max(0, indent)) + line);
        if (id) map[lines.length] = id;
      }
    };
    const open = (s, id) => {
      emit(s, id);
      emit("{", id);
      indent++;
    };
    const close = (id) => {
      indent--;
      emit("}", id);
    };
    const all = [];
    for (const m of file.methods)
      walk(m.blocks, (b) => {
        if (!b.disabled) all.push(b);
      });
    const hasLemon = all.some((b) => registry[b.kind].dependency === "lemon"),
      hasPhone = all.some((b) => registry[b.kind].dependency === "ifruit");
    emit(
      "// Generated by BlockForge. Edit the visual project to keep blocks and source in sync.",
    );
    for (const ns of [
      ...new Set([
        "System",
        "System.Windows.Forms",
        "GTA",
        "GTA.Math",
        "GTA.Native",
        ...(hasLemon ? ["LemonUI", "LemonUI.Menus"] : []),
        ...(hasPhone ? ["iFruitAddon2"] : []),
        ...project.usings,
      ]),
    ])
      emit("using " + ns + ";");
    emit();
    open("namespace " + project.namespace);
    open("public class " + file.className + " : Script");
    if (hasLemon)
      emit("private readonly ObjectPool _bfPool = new ObjectPool();");
    for (const b of all) {
      if (b.kind === "menu")
        emit("private NativeMenu " + b.values.name + ";", b.id);
      if (b.kind === "menuCheckbox")
        emit("private NativeCheckboxItem " + b.values.name + ";", b.id);
      if (b.kind === "phone")
        emit("private CustomiFruit " + b.values.name + ";", b.id);
    }
    function generate(blocks, ctx) {
      for (const b of blocks) {
        if (b.disabled) continue;
        const v = b.values,
          id = b.id,
          def = registry[b.kind];
        if (def.dependency && !project.frameworks.includes(def.dependency))
          diagnostics.push({
            severity: "error",
            code: "BF100",
            message:
              def.category +
              " is required by " +
              def.label +
              ". Enable it in Frameworks.",
            file: file.name,
            blockId: id,
          });
        if (def.scope === "fields" && ctx !== "fields")
          diagnostics.push({
            severity: "error",
            code: "BF101",
            message: def.label + " belongs in Class fields.",
            file: file.name,
            blockId: id,
          });
        if (ctx === "fields" && def.scope !== "fields" && b.kind !== "comment")
          diagnostics.push({
            severity: "error",
            code: "BF102",
            message: "Executable blocks belong in a method.",
            file: file.name,
            blockId: id,
          });
        if (b.kind === "key" && ctx !== "keyDown" && ctx !== "keyUp")
          diagnostics.push({
            severity: "error",
            code: "BF103",
            message: "Key blocks require a KeyDown or KeyUp handler.",
            file: file.name,
            blockId: id,
          });
        switch (b.kind) {
          case "notify":
            emit("GTA.UI.Notification.Show(" + ex(v, "message") + ");", id);
            break;
          case "subtitle":
            emit(
              "GTA.UI.Screen.ShowSubtitle(" +
                ex(v, "message") +
                ", " +
                v.duration +
                ");",
              id,
            );
            break;
          case "wanted":
            emit("Game.Player.WantedLevel = " + v.level + ";", id);
            break;
          case "health":
            emit("Game.Player.Character.Health = " + ex(v, "value") + ";", id);
            break;
          case "armor":
            emit("Game.Player.Character.Armor = " + ex(v, "value") + ";", id);
            break;
          case "money":
            emit("Game.Player.Money = " + ex(v, "value") + ";", id);
            break;
          case "invincible":
            emit(
              "Game.Player.Character.IsInvincible = " + ex(v, "value") + ";",
              id,
            );
            break;
          case "teleport":
            emit(
              "Game.Player.Character.Position = new Vector3((float)(" +
                ex(v, "x") +
                "), (float)(" +
                ex(v, "y") +
                "), (float)(" +
                ex(v, "z") +
                "));",
              id,
            );
            break;
          case "weather":
            emit("World.Weather = Weather." + v.weather + ";", id);
            break;
          case "time":
            emit(
              "World.CurrentTimeOfDay = new TimeSpan(" +
                v.hour +
                ", " +
                v.minute +
                ", 0);",
              id,
            );
            break;
          case "vehicle":
          case "ped": {
            const model = "_model_" + id.replace(/-/g, "");
            emit("var " + model + " = new Model(" + ex(v, "model") + ");", id);
            emit(model + ".Request(1000);", id);
            emit(
              (b.kind === "vehicle" ? "Vehicle" : "Ped") +
                " " +
                v.name +
                " = null;",
              id,
            );
            open("if (" + model + ".IsValid && " + model + ".IsLoaded)", id);
            emit(
              v.name +
                " = World." +
                (b.kind === "vehicle" ? "CreateVehicle" : "CreatePed") +
                "(" +
                model +
                ", " +
                ex(v, "position") +
                ");",
              id,
            );
            close(id);
            emit(model + ".MarkAsNoLongerNeeded();", id);
            break;
          }
          case "deleteEntity":
            emit(
              "if (" +
                ex(v, "entity") +
                " != null) " +
                ex(v, "entity") +
                ".Delete();",
              id,
            );
            break;
          case "repair":
            emit(
              "if (" +
                ex(v, "vehicle") +
                " != null) " +
                ex(v, "vehicle") +
                ".Repair();",
              id,
            );
            break;
          case "blip":
            emit(
              "var " +
                v.name +
                " = World.CreateBlip(" +
                ex(v, "position") +
                ");",
              id,
            );
            emit(v.name + ".Name = " + ex(v, "label") + ";", id);
            break;
          case "weapon":
            emit(
              "Game.Player.Character.Weapons.Give(WeaponHash." +
                v.hash +
                ", " +
                v.ammo +
                ", true, true);",
              id,
            );
            break;
          case "if":
          case "ifElse":
            open("if (" + ex(v, "condition") + ")", id);
            generate(b.children, ctx);
            close(id);
            if (b.kind === "ifElse") {
              open("else", id);
              generate(b.otherwise, ctx);
              close(id);
            }
            break;
          case "repeat":
            open(
              "for (int " +
                v.variable +
                " = 0; " +
                v.variable +
                " < " +
                ex(v, "count") +
                "; " +
                v.variable +
                "++)",
              id,
            );
            generate(b.children, ctx);
            close(id);
            break;
          case "while":
            open("while (" + ex(v, "condition") + ")", id);
            generate(b.children, ctx);
            close(id);
            diagnostics.push({
              severity: "warning",
              code: "BF200",
              message:
                "Ensure this loop terminates or yields; a blocking loop can freeze a script.",
              file: file.name,
              blockId: id,
            });
            break;
          case "foreach":
            open(
              "foreach (" +
                v.type +
                " " +
                v.variable +
                " in " +
                ex(v, "collection") +
                ")",
              id,
            );
            generate(b.children, ctx);
            close(id);
            break;
          case "try":
            open("try", id);
            generate(b.children, ctx);
            close(id);
            open("catch (Exception " + v.exception + ")", id);
            generate(b.otherwise, ctx);
            close(id);
            break;
          case "key":
            open("if (e.KeyCode == Keys." + v.key + ")", id);
            generate(b.children, ctx);
            close(id);
            break;
          case "return":
            emit("return" + (v.value ? " " + v.value : "") + ";", id);
            break;
          case "break":
          case "continue":
            emit(b.kind + ";", id);
            break;
          case "wait":
            emit("Script.Wait(" + ex(v, "duration") + ");", id);
            break;
          case "field":
            emit(
              "private " + v.type + " " + v.name + " = " + ex(v, "value") + ";",
              id,
            );
            break;
          case "variable":
            emit(v.type + " " + v.name + " = " + ex(v, "value") + ";", id);
            break;
          case "assign":
            emit(ex(v, "target") + " = " + ex(v, "value") + ";", id);
            break;
          case "increment":
            emit(ex(v, "target") + " += " + ex(v, "value") + ";", id);
            break;
          case "call":
            emit(v.method + "(" + args(v) + ");", id);
            break;
          case "api":
            emit(
              (v.result ? "var " + v.result + " = " : "") +
                (v.target ? v.target + "." : "") +
                v.member +
                "(" +
                args(v) +
                ");",
              id,
            );
            break;
          case "new":
            emit(
              "var " + v.name + " = new " + v.type + "(" + args(v) + ");",
              id,
            );
            break;
          case "comment":
            emit(
              String(v.text)
                .split(/\r?\n/)
                .map((x) => "// " + x)
                .join("\n"),
              id,
            );
            break;
          case "raw":
          case "member":
            emit(v.code, id);
            break;
          case "menu":
            emit(
              v.name +
                " = new NativeMenu(" +
                ex(v, "title") +
                ", " +
                ex(v, "subtitle") +
                ", " +
                ex(v, "description") +
                ");",
              id,
            );
            emit("_bfPool.Add(" + v.name + ");", id);
            break;
          case "menuItem":
            emit(
              "var " +
                v.name +
                " = new NativeItem(" +
                ex(v, "title") +
                ", " +
                ex(v, "description") +
                ");",
              id,
            );
            if (v.handler)
              emit(v.name + ".Activated += " + v.handler + ";", id);
            emit(v.menu + ".Add(" + v.name + ");", id);
            break;
          case "menuCheckbox":
            emit(
              v.name +
                " = new NativeCheckboxItem(" +
                ex(v, "title") +
                ", " +
                ex(v, "value") +
                ");",
              id,
            );
            emit(v.menu + ".Add(" + v.name + ");", id);
            break;
          case "menuToggle":
            emit(v.menu + ".Visible = !" + v.menu + ".Visible;", id);
            break;
          case "menuVisible":
            emit(v.menu + ".Visible = " + ex(v, "value") + ";", id);
            break;
          case "menuProcess":
            emit("_bfPool.Process();", id);
            break;
          case "phone":
            emit(v.name + " = new CustomiFruit();", id);
            break;
          case "contact":
            emit(
              "var " +
                v.name +
                " = new iFruitContact(" +
                ex(v, "label") +
                ") { DialTimeout = " +
                v.timeout +
                ", Active = true };",
              id,
            );
            if (v.handler) emit(v.name + ".Answered += " + v.handler + ";", id);
            emit(v.phone + ".Contacts.Add(" + v.name + ");", id);
            break;
          case "phoneUpdate":
            emit(v.phone + ".Update();", id);
            break;
          case "phoneClose":
            emit(v.phone + ".Close(" + v.delay + ");", id);
            break;
          case "native": {
            const type =
              v.returnType && v.returnType !== "void"
                ? "<" + v.returnType + ">"
                : "";
            emit(
              (v.result ? "var " + v.result + " = " : "") +
                "Function.Call" +
                type +
                "(Hash." +
                v.hash +
                ((v.args || []).length ? ", " + args(v) : "") +
                ");",
              id,
            );
            break;
          }
          default:
            throw new Error("Unsupported block " + b.kind);
        }
      }
    }
    for (const m of file.methods.filter((m) => m.event === "fields"))
      generate(m.blocks, "fields");
    emit();
    open("public " + file.className + "()");
    for (const m of file.methods) {
      const events = {
        tick: "Tick",
        keyDown: "KeyDown",
        keyUp: "KeyUp",
        aborted: "Aborted",
      };
      if (Object.hasOwn(events, m.event))
        emit(events[m.event] + " += " + m.name + ";");
    }
    for (const m of file.methods.filter((m) => m.event === "constructor"))
      generate(m.blocks, "constructor");
    close();
    for (const m of file.methods.filter(
      (m) => !["fields", "constructor"].includes(m.event),
    )) {
      emit();
      const ps =
        m.event === "phoneAnswered"
          ? "iFruitContact contact"
          : ["keyDown", "keyUp"].includes(m.event)
            ? "object sender, KeyEventArgs e"
            : ["tick", "aborted", "menuClick"].includes(m.event)
              ? "object sender, EventArgs e"
              : m.parameters || "";
      open(
        "private " +
          (m.event === "method" ? m.returnType || "void" : "void") +
          " " +
          m.name +
          "(" +
          ps +
          ")",
      );
      generate(m.blocks, m.event);
      close();
    }
    close();
    close();
    files.push({
      name: file.name,
      source: lines.join("\n") + "\n",
      map,
      lineCount: lines.length,
    });
  }
  return {
    files,
    diagnostics,
    lineCount: files.reduce((n, f) => n + f.lineCount, 0),
  };
}
export function projectXml(p) {
  const refs = [
    "ScriptHookVDotNet3",
    ...(p.frameworks.includes("lemon") ? ["LemonUI.SHVDN3"] : []),
    ...(p.frameworks.includes("ifruit") ? ["iFruitAddon2"] : []),
    ...p.references.map((r) => r.replace(/\.dll$/i, "")),
  ];
  return `<Project Sdk="Microsoft.NET.Sdk">\n  <PropertyGroup>\n    <TargetFramework>net48</TargetFramework>\n    <LangVersion>latest</LangVersion>\n    <OutputType>Library</OutputType>\n    <AssemblyName>${p.name}</AssemblyName>\n    <Version>${p.version}</Version>\n    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>\n  </PropertyGroup>\n  <ItemGroup>\n    <Reference Include="System.Windows.Forms" />\n    <Reference Include="System.Drawing" />\n${refs.map((r) => `    <Reference Include="${r}"><HintPath>lib\\${r}.dll</HintPath><Private>false</Private></Reference>`).join("\n")}\n    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies.net48" Version="1.0.3" PrivateAssets="all" />\n  </ItemGroup>\n</Project>\n`;
}
